### ISSUE TITLE
[BUG] Requestor cannot comment in request under review

### ISSUE THREAD

**Issue by RadovanTomik** [BBMRI-ERIC/negotiator-frontend#287]
**Describe the bug**
The Author of a request cannot post a comment if the status is "under review"
**How to reproduce**
Submit a request and try to comment without Admin role.
**What happens**
Button is gray
**What should happen**
The Author should be able to post a commment

**Comment by tmilost** [comment]
cant reproduce,
maybe it is not enabled in negotiation
it only depends on 2 variable and if there is text or attachment and if recipientId is selected
`"publicPostsEnabled": true,
  "privatePostsEnabled": false`
