### ISSUE TITLE
[FEATURE] Add correct labels in the Negotiations page 

### ISSUE THREAD

**Issue by svituz** [BBMRI-ERIC/negotiator-frontend#40]
**Brief description.**
Currently, the Negotiation page uses, as labels of the sections and of the fields of the negotiation, the ids of the access criteria. These ids cannot be used as labels to be shown to the user

**Desired functionality acceptance criteria**
The labels should be the same as the ones of the access criteria. For example, ETHICS-VOTE should be "ETHICS VOTE", "ethics-vote-attachment" "Ethics Vote Attachment" and so on.

**Comment by tmilost-bbmri-eric** [comment]
We need to see if we want to change the name on the front-end or the back-end, since we get this information from the database @RadovanTomik
